In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [2]:
SEED = 122721

In [3]:
iris = datasets.load_iris()
X = iris.data
Y = iris.target

In [4]:
# Split in a training and validation/test set
X_train, X_test, Y_train, Y_test = train_test_split(
  X, Y, random_state=SEED, shuffle=True
)

In [5]:
# Fix import path
import sys
from os import path
sys.path.insert(0, path.abspath(path.join("..")))

from models.traditional.naive_bayes import GaussianNaiveBayes

In [6]:
# Initialize model
Y_train = np.expand_dims(Y_train, axis=1)

naive_bayes = GaussianNaiveBayes(X_train, Y_train)
naive_bayes.fit()

In [7]:
# Run on validation/test set
prediction = naive_bayes.predict(X_test)

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [9]:
print(accuracy_score(Y_test, prediction))

0.9736842105263158


In [10]:
# Matrix elements C(i, j) represent the number of observations
#   known to be in group i but predicted to be in group j by the model.
print(confusion_matrix(Y_test, prediction))

[[14  0  0]
 [ 0 14  0]
 [ 0  1  9]]
